credentials:
  system:
    domainCredentials:
    - credentials:
      - azure:
          azureEnvironmentName: "Azure"
          clientId: ${AZURE_CLIENT_ID}
          clientSecret: ${AZURE_CLIENT_SECRET}
          id: "azure-vm-agents"
          scope: GLOBAL
          subscriptionId: ${AZURE_SUBSCRIPTION_ID}
          tenant: ${AZURE_TENANT_ID}
      - usernamePassword:
          id: "jenkins-agents"
          password: ${JENKINS_AGENTS_PASSWORD}
          scope: GLOBAL
          username: ${JENKINS_AGENTS_USERNAME}
jenkins:
  clouds:
  - azureVM:
      azureCredentialsId: "azure-vm-agents"
      configurationStatus: "pass"
      deploymentTimeout: 1200
      maxVirtualMachinesLimit: 10
      name: "azure-vm-agents"
      newResourceGroupName: ${AZURE_RESOURCE_GROUP}
      resourceGroupReferenceType: "new"
      vmTemplates:
      - builtInImage: "Ubuntu 22.04 LTS"
        credentialsId: "jenkins-agents"
        diskType: "managed"
        doNotUseMachineIfInitFails: true
        executeInitScriptAsRoot: true
        imageReference:
          version: "latest"
        imageTopLevelType: "basic"
        javaPath: "java"
        labels: "ubuntu-22.04"
        location: "East US"
        maxVirtualMachinesLimit: 1
        maximumDeploymentSize: 10
        newStorageAccountName: "jndczujlemitg9b83bj0cduq"
        noOfParallelJobs: 1
        osType: "Linux"
        retentionStrategy:
          azureVMCloudRetentionStrategy:
            idleTerminationMinutes: 5
        storageAccountNameReferenceType: "new"
        storageAccountType: "Standard_LRS"
        templateName: "all-in-one"
        usageMode: NORMAL
        virtualMachineSize: "Standard_B1ls"
  labelAtoms:
  - name: "built-in"
  - name: "ubuntu-22.04"
  log:
    recorders:
    - loggers:
      - level: "WARNING"
        name: "com.microsoft.azure.vmagent"
      name: "Azure VM Agent (Auto)"
  systemMessage: "This is a demo Jenkins instance configured with Jenkins Configuration as Code."
  disabledAdministrativeMonitors:
    - "jenkins.diagnostics.ControllerExecutorsNoAgents"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: ${JENKINS_ADMIN_USERNAME}
        password: ${JENKINS_ADMIN_PASSWORD}
        name: ${JENKINS_ADMIN_NAME}
        properties:
        - "apiToken"
        - "consoleUrlProvider"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "theme"
        - "timezone"
        - "experimentalFlags"
        - mailer:
            emailAddress: ${JENKINS_ADMIN_EMAIL}
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  scriptApproval:
    approvedScriptHashes:
    - "SHA512:48f7039e9f4975738772cbffc37807725eb4fc21c120c3c3ed11b4480929c072169ad764356c88a1355c4fa938f62c72d2c5498c9cd872db9ff9c7a22bb2fd41"
unclassified:
  location:
    adminAddress: ${JENKINS_ADMIN_EMAIL}
    url: ${JENKINS_URL}
  locale:
    ignoreAcceptLanguage: true
    systemLocale: ${JENKINS_LOCALE}
jobs:
  - script: >
      folder('testjobs')
  - script: >
      pipelineJob('testjobs/hello-world') {
        definition {
          cps {
            script("""\
              pipeline {
                agent { label 'ubuntu-22.04' }
                stages {
                  stage ('test') {
                    steps {
                      echo "Hello World!"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }
